# Generated by Django 5.1.4 on 2024-12-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0004_alter_game_age_limited'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100, unique=True), unique=True),
        ),
    ]
